ARG BASE_IMAGE=philippvk/isaac-quickstart-mlonmcu-min
ARG MLONMCU_TEMPLATE=environment_docker.yml.j2

FROM ${BASE_IMAGE} AS builder
LABEL maintainer="MLonMCU Developers"

ADD ${MLONMCU_TEMPLATE} /tmp/environment.yml.j2

RUN mlonmcu init --template /tmp/environment.yml.j2 --non-interactive /environment --clone-models
ENV MLONMCU_HOME=/environment

RUN mlonmcu setup -g

RUN . /venv/bin/activate && pip install -r /environment/requirements_addition.txt --no-cache-dir

RUN . /venv/bin/activate && mlonmcu setup -v

VOLUME /environment

ENTRYPOINT ["/work/mlonmcu_script.sh"]
CMD ["help"]
ENV LD_LIBRARY_PATH="/usr/local/lib/:$LD_LIBRARY_PATH"
