FROM ubuntu:22.04 AS hls_image
# Hint: 20.04 does not work as we need Py3.10+ and GCC11
LABEL maintainer="Philipp van Kempen"

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get -qqq -y install --no-install-recommends git wget unzip vim openssh-client build-essential gnupg \
        ca-certificates gpg wget apt-transport-https curl build-essential manpages-dev software-properties-common \
        python3-pip python3-venv python3-dev \
	yosys-dev openjdk-21-jdk maven \
    && apt-get clean \
    && rm -rf /var/cache/apt/archives/ \
    && rm -rf /var/lib/apt/lists

RUN echo "deb https://repo.scala-sbt.org/scalasbt/debian all main" \
        | tee /etc/apt/sources.list.d/sbt.list \
    && curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823" \
        | gpg --no-default-keyring --keyring gnupg-ring:/etc/apt/trusted.gpg.d/scalasbt-release.gpg --import \
    && chmod 644 /etc/apt/trusted.gpg.d/scalasbt-release.gpg \
    && apt update \
    && apt install -qqq -y sbt --no-install-recommends \
    && rm -rf /var/cache/apt/archives/ \
    && rm -rf /var/lib/apt/lists

# Install modern CMake
ARG ENABLE_CMAKE="true"
ARG CMAKE_REPO="https://github.com/Kitware/CMake"
ARG CMAKE_VERSION="3.22.2"
ARG CMAKE_TARGET="Linux-x86_64"
RUN if [ "${ENABLE_CMAKE}" = "true" ] ; \
    then \
    cd /tmp \
    && wget -q -O cmake.sh ${CMAKE_REPO}/releases/download/v${CMAKE_VERSION}/cmake-${CMAKE_VERSION}-${CMAKE_TARGET}.sh \
    && mkdir -p /opt/cmake/ \
    && sh ./cmake.sh --skip-license --exclude-subdir --prefix=/opt/cmake/ \
    && rm ./cmake.sh ; \
    fi
ENV PATH="/opt/cmake/bin/:$PATH:"

RUN mkdir /isax-tools

COPY deps /isax-tools/deps
COPY nailgun /isax-tools/nailgun

RUN python3 -m venv /isax-tools/venv

ENV PATH=/isax-tools/venv/bin:${PATH}

RUN . /isax-tools/venv/bin/activate && pip install kconfiglib pyyaml pyelftools

RUN cd /isax-tools/deps/scaie-v/ && mvn package

COPY ./docker/hls_script.sh /isax-tools/hls_script.sh

ENTRYPOINT ["/isax-tools/hls_script.sh"]

# FROM hls_image AS openlane_image
# RUN git clone --depth 1 https://github.com/The-OpenROAD-Project/OpenLane.git /isax-tools/OpenLane
# RUN cd /isax-tools/OpenLane/ && make
# RUN cd /isax-tools/OpenLane/ && make test
