ARG BASE_IMAGE=philippvk/isaac-quickstart-base
FROM ${BASE_IMAGE} AS builder
LABEL maintainer="ETISS Developers"

ARG CLONE_DEPTH=1
ENV PYTHONPATH=/work/M2-ISA-R
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y --no-install-recommends ca-certificates gnupg \
           build-essential cmake make python3 zlib1g wget subversion zip unzip git ninja-build python3-dev python3-pip python3-venv libssl-dev libboost-all-dev zip unzip && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir /work
COPY M2-ISA-R/ /work/M2-ISA-R

RUN python3 -m venv /work/venv
RUN . /work/venv/bin/activate && pip3 install -r /work/M2-ISA-R/requirements.txt

# ETISS Perf specific
RUN git config --global url."https://github.com/".insteadOf git@github.com:
RUN cd /work/ && git clone https://github.com/tum-ei-eda/PerformanceSimulation_workspace.git /work/perf_sim_workspace -b xisaac_gen --recursive

COPY ./docker/etiss_perf_script.sh /work/etiss_perf_script.sh

ENTRYPOINT ["/work/etiss_perf_script.sh"]
CMD ["help"]
