# Debian 12
# FROM debian:bookworm-slim AS builder
# Debian 11
# FROM debian:bullseye-slim AS builder
FROM ubuntu:20.04 AS builder
LABEL maintainer="ISAAC Developers"

ARG CLONE_DEPTH=1
ENV IN_FULL_DOCKER=1
ENV SEAL5_HOME=/work/llvm/
ENV PYTHONPATH=/work/seal5/:/work/M2-ISA-R
ENV PATH="/opt/cmake/bin/:$PATH:"
ENV DEBIAN_FRONTEND=noninteractive

# Install build dependencies of llvm.
# First, Update the apt's source list and include the sources of the packages.
RUN grep deb /etc/apt/sources.list | \
    sed 's/^deb/deb-src /g' >> /etc/apt/sources.list
# Install compiler, python and subversion.
# Install compiler, python and subversion.
RUN apt-get update && \
    apt-get install -y --no-install-recommends ca-certificates gnupg \
        build-essential make python3 zlib1g wget subversion git ninja-build python3-dev \
        gpg apt-transport-https curl manpages-dev software-properties-common \
	      yosys-dev openjdk-21-jdk maven vim openssh-client \
        python3-pip python3-venv libssl-dev libboost-all-dev zip unzip ccache \
        wget unzip vim openssh-client \
        g++ graphviz graphviz libgraphviz-dev doxygen libtinfo-dev zlib1g-dev \
        autoconf automake autotools-dev curl python3 libmpc-dev libmpfr-dev libgmp-dev gawk build-essential \
        bison flex texinfo gperf libtool patchutils bc zlib1g-dev libexpat-dev ca-certificates \
        virtualenv git python3-dev python3-pip python3-setuptools python3-venv libtinfo5 libzstd-dev \
        gcc libedit-dev libxml2-dev libopenblas-dev liblapack-dev gfortran unzip ninja-build python-is-python3 device-tree-compiler libboost-all-dev \
        libfl-dev lsb-release libelf-dev libssl-dev poppler-utils sudo\
    && apt-get clean \
    && rm -rf /var/cache/apt/archives/ \
    && rm -rf /var/lib/apt/lists

# Install modern CMake
ARG ENABLE_CMAKE="true"
ARG CMAKE_REPO="https://github.com/Kitware/CMake"
ARG CMAKE_VERSION="3.22.2"
ARG CMAKE_TARGET="Linux-x86_64"
RUN if [ "${ENABLE_CMAKE}" = "true" ] ; \
    then \
    cd /tmp \
    && wget -O cmake.sh ${CMAKE_REPO}/releases/download/v${CMAKE_VERSION}/cmake-${CMAKE_VERSION}-${CMAKE_TARGET}.sh \
    && mkdir -p /opt/cmake/ \
    && sh ./cmake.sh --skip-license --exclude-subdir --prefix=/opt/cmake/ \
    && rm ./cmake.sh ; \
    fi
ENV PATH="/opt/cmake/bin/:$PATH:"




RUN echo "deb https://repo.scala-sbt.org/scalasbt/debian all main" \
        | tee /etc/apt/sources.list.d/sbt.list \
    && curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823" \
        | gpg --no-default-keyring --keyring gnupg-ring:/etc/apt/trusted.gpg.d/scalasbt-release.gpg --import \
    && chmod 644 /etc/apt/trusted.gpg.d/scalasbt-release.gpg \
    && apt update \
    && apt install -qqq -y sbt --no-install-recommends \
    && rm -rf /var/cache/apt/archives/ \
    && rm -rf /var/lib/apt/lists

ENV LD_LIBRARY_PATH="/usr/local/lib/:$LD_LIBRARY_PATH"
RUN ln -s /usr/local/lib/libmgclient.so /usr/local/lib/libmgclient.so.2

# Install Miniforge (no Python included)
RUN ARCH=$(uname -m) && \
    if [ "$ARCH" = "x86_64" ]; then \
        URL="https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-x86_64.sh"; \
    elif [ "$ARCH" = "aarch64" ]; then \
        URL="https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-aarch64.sh"; \
    else \
        echo "Unsupported arch: $ARCH"; exit 1; \
    fi && \
    wget $URL -O miniforge.sh && \
    bash miniforge.sh -b -p /opt/conda && \
    rm miniforge.sh

ENV PATH="/opt/conda/bin:$PATH"

# Create minimal Python 3.10 env
RUN conda install --revision 0 && conda install python=3.10 && conda create -y -n py310 python=3.10 && \
    conda clean -a -y -p -f

# Arguments for user creation
ARG USER_UID=1000
ARG USER_GID=1000
ARG USERNAME=isaac-dev

# Delete user if USER already exists (Ubuntu 24 has ubuntu user by default with UID 1000)
RUN if id -u $USER_UID ; then userdel `id -un $USER_UID` ; fi

# Create the user
RUN groupadd --gid $USER_GID $USERNAME \
&& useradd --uid $USER_UID --gid $USER_GID -m $USERNAME \
&& mkdir -p /etc/sudoers.d \
# [Optional] Add sudo support. Omit if you don't need to install software after connecting.
&& echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
&& chmod 0440 /etc/sudoers.d/$USERNAME


# Change ownership of home directory to system $USER
RUN chown -R $USERNAME:$USERNAME /opt

# Activate environment
# SHELL ["bash", "-c"]
RUN echo "source activate py310" >> ~/.bashrc
ENV CONDA_DEFAULT_ENV=py310
ENV PATH="/opt/conda/envs/py310/bin:$PATH"

USER ${USERNAME}

# Install Rust for the user ${USERNAME}
RUN curl https://sh.rustup.rs -sSf | bash -s -- -y
ENV PATH="/home/${USERNAME}/.cargo/bin:${PATH}"
ENV PYTHON_EXE=python3.10
