ARG BASE_IMAGE=philippvk/isaac-quickstart-extra
FROM ${BASE_IMAGE} AS builder
LABEL maintainer="ISAAC Developers"

ARG CLONE_DEPTH=1
ENV IN_FULL_DOCKER=1
ENV SEAL5_HOME=/work/llvm/
ENV PYTHONPATH=/work/seal5/:/work/M2-ISA-R
ENV PATH="/opt/cmake/bin/:$PATH:"
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y --no-install-recommends ca-certificates gnupg \
        build-essential make python3 zlib1g wget subversion git ninja-build python3-dev \
        gpg apt-transport-https curl manpages-dev software-properties-common \
	      yosys-dev openjdk-21-jdk maven vim openssh-client \
        python3-pip python3-venv libssl-dev libboost-all-dev zip unzip ccache \
        wget unzip vim openssh-client \
        g++ graphviz graphviz libgraphviz-dev doxygen libtinfo-dev zlib1g-dev \
        autoconf automake autotools-dev curl python3 libmpc-dev libmpfr-dev libgmp-dev gawk build-essential \
        bison flex texinfo gperf libtool patchutils bc zlib1g-dev libexpat-dev ca-certificates \
        virtualenv git python3-dev python3-pip python3-setuptools python3-venv libtinfo5 libzstd-dev \
        gcc libedit-dev libxml2-dev libopenblas-dev liblapack-dev gfortran unzip ninja-build python-is-python3 device-tree-compiler libboost-all-dev \
        libfl-dev lsb-release libelf-dev libssl-dev poppler-utils \
    && apt-get clean \
    && rm -rf /var/cache/apt/archives/ \
    && rm -rf /var/lib/apt/lists

COPY --from=philippvk/isaac-quickstart-etiss /work /work
COPY --from=philippvk/isaac-quickstart-seal5 /work /work
COPY --from=philippvk/isaac-quickstart-mlonmcu /work /work
COPY --from=philippvk/isaac-quickstart-hls /isax-tools /isax-tools

CMD ["help"]


ENV MLONMCU_HOME=/environment
COPY --from=philippvk/isaac-quickstart-mlonmcu /environment /environment
COPY --from=philippvk/isaac-quickstart-mlonmcu /venv /venv
COPY --from=philippvk/isaac-quickstart-mlonmcu /mlonmcu /mlonmcu

COPY ./docker/full_script.sh /work/full_script.sh

ENTRYPOINT ["/work/full_script.sh"]
ENV LD_LIBRARY_PATH="/usr/local/lib/:$LD_LIBRARY_PATH"
