ARG BASE_IMAGE=philippvk/isaac-quickstart-extra
FROM ${BASE_IMAGE} AS builder
LABEL maintainer="ISAAC Developers"

ARG CLONE_DEPTH=1

# Install compiler, python and subversion.
RUN apt-get update && \
    apt-get install -y --no-install-recommends ca-certificates gnupg \
        build-essential make python3 zlib1g wget subversion git ninja-build python3-dev \
        gpg apt-transport-https curl manpages-dev software-properties-common \
	      yosys-dev openjdk-21-jdk maven vim openssh-client \
        python3-pip python3-venv libssl-dev libboost-all-dev zip unzip ccache \
        wget unzip vim openssh-client \
        g++ graphviz graphviz libgraphviz-dev doxygen libtinfo-dev zlib1g-dev \
        autoconf automake autotools-dev curl python3 libmpc-dev libmpfr-dev libgmp-dev gawk build-essential \
        bison flex texinfo gperf libtool patchutils bc zlib1g-dev libexpat-dev ca-certificates \
        virtualenv git python3-dev python3-pip python3-setuptools python3-venv libtinfo5 libzstd-dev \
        gcc libedit-dev libxml2-dev libopenblas-dev liblapack-dev gfortran unzip ninja-build python-is-python3 device-tree-compiler libboost-all-dev \
        libfl-dev lsb-release libelf-dev libssl-dev poppler-utils \
    && apt-get clean \
    && rm -rf /var/cache/apt/archives/ \
    && rm -rf /var/lib/apt/lists

RUN echo "deb https://repo.scala-sbt.org/scalasbt/debian all main" \
        | tee /etc/apt/sources.list.d/sbt.list \
    && curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823" \
        | gpg --no-default-keyring --keyring gnupg-ring:/etc/apt/trusted.gpg.d/scalasbt-release.gpg --import \
    && chmod 644 /etc/apt/trusted.gpg.d/scalasbt-release.gpg \
    && apt update \
    && apt install -qqq -y sbt --no-install-recommends \
    && rm -rf /var/cache/apt/archives/ \
    && rm -rf /var/lib/apt/lists

COPY --from=philippvk/isaac-quickstart-hls /isax-tools /isax-tools

CMD ["help"]

ENV MLONMCU_HOME=/environment

COPY ./docker/min_script.sh /work/min_script.sh

ENTRYPOINT ["/work/min_script.sh"]
ENV LD_LIBRARY_PATH="/usr/local/lib/:$LD_LIBRARY_PATH"
