#!/bin/bash

set -e

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
TOP_DIR=$(dirname $SCRIPT_DIR)
INSTALL_DIR=$TOP_DIR/install
MGCLIENT_DIR=$TOP_DIR/mgclient
MGCLIENT_BUILD_DIR=$MGCLIENT_DIR/build
MGCLIENT_INSTALL_DIR=$INSTALL_DIR/mgclient
CMAKE_BUILD_TYPE=Release

mkdir -p $MGCLIENT_BUILD_DIR

cmake -B $MGCLIENT_BUILD_DIR -S $MGCLIENT_DIR -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE -DCMAKE_INSTALL_PREFIX:PATH=$MGCLIENT_INSTALL_DIR

cmake --build $MGCLIENT_BUILD_DIR -j$(nproc)
cmake --install $MGCLIENT_BUILD_DIR
