#!/bin/bash

set -e

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]:-${(%):-%N}}" )" &> /dev/null && pwd )
TOP_DIR=$(dirname $SCRIPT_DIR)
INSTALL_DIR=${INSTALL_DIR:-$TOP_DIR/install}
ETISS_DIR=${ETISS_DIR:-$TOP_DIR/etiss}
ETISS_BUILD_DIR=$ETISS_DIR/build
ETISS_INSTALL_DIR=${ETISS_INSTALL_DIR:-$INSTALL_DIR/etiss}
CMAKE_BUILD_TYPE=${ETISS_BUILD_TYPE:-Release}
CCACHE=${CCACHE:-1}
CMAKE_EXTRA_ARGS=("-DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE")
if [[ "$CCACHE" -eq 1 ]]
then
    CMAKE_EXTRA_ARGS+=("-DCMAKE_C_COMPILER_LAUNCHER=ccache")
    CMAKE_EXTRA_ARGS+=("-DCMAKE_CXX_COMPILER_LAUNCHER=ccache")
fi

mkdir -p $ETISS_BUILD_DIR

echo cmake -B $ETISS_BUILD_DIR -S $ETISS_DIR -DCMAKE_INSTALL_PREFIX:PATH=$ETISS_INSTALL_DIR "${CMAKE_EXTRA_ARGS[@]}"
cmake -B $ETISS_BUILD_DIR -S $ETISS_DIR -DCMAKE_INSTALL_PREFIX:PATH=$ETISS_INSTALL_DIR "${CMAKE_EXTRA_ARGS[@]}"

cmake --build $ETISS_BUILD_DIR -j$NPROC
cmake --install $ETISS_BUILD_DIR
